"""<user table >

Revision ID: 3431a016f64c
Revises: 9221f1f13101
Create Date: 2023-10-02 01:22:27.219462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3431a016f64c'
down_revision = '9221f1f13101'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblusers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tblusers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tblusers_email'), ['email'], unique=True)

    op.drop_table('user_group_association')
    op.drop_table('user')
    op.drop_table('group')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_group_association',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('group_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], name='fk_user_group_association_group_id_group'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_user_group_association_user_id_user'),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    with op.batch_alter_table('tblusers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tblusers_email'))

    op.drop_table('tblusers')
    # ### end Alembic commands ###
